#! /usr/bin/env node

/**
 * [nct : node cli tools]
 * @author: xgqfrms
 * @date: 2017-01-01
 */
console.log(`hello world!`);

const nct = require('./shell');

let username = process.argv[2] ? process.argv[2] : `xgqfrms`;
repo = process.argv[3] ? process.argv[3] : `cdn`;

nct(username, repo);



/*


"bin": {
    "hello" : "hello.js"
}

"bin": "./bin.js",

bin": {
    "nct": "nctcli",
    "nct_js": "nctcli.js",
},


{
    "name": "node-cli-tools",
    "version": "1.1.1",
    "private": true,
    "bin": {
        "nct": "nctcli"
    },
    "scripts": {
        "nct": "node nctcli",
        "start": "node nctcli"
    },
    "dependencies": {
        "colors": "^1.1.2",
        "node-fetch": "^1.7.1"
    }
}


*/